export const productFields = {

    "Marine Insurance": [
        { label: "Full Name", id: "fullName", type: "text", required: true },
        { label: "ID/Passport Number", id: "idPassport", type: "text", required: true },
        { label: "PIN Number", id: "pinNumber", type: "text" },
        { label: "Occupation", id: "occupation", type: "text" },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Postal Code", id: "postalCode", type: "number" },
        { label: "Town", id: "town", type: "text" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Telephone/Mobile", id: "phone", type: "text" },
        { label: "Category of Cargo", id: "cargoCategory", type: "checkboxes", options: ["Chemicals/Pharmaceuticals", "Food", "Machinery/Vehicles", "Textile", "Other"] },
        { label: "Other Cargo Category Details", id: "otherCargoDetails", type: "text", showIf: { field: "cargoCategory", value: "Other" } },
        { label: "Cargo Description", id: "cargoDescription", type: "textarea" },
        { label: "Select Packaging Type(s)", id: "packagingTypes", type: "checkboxes", options: ["Containerized", "Non-containerized", "Boxes", "Cartons", "Bags", "Drums", "Bottled", "Crates", "Locked", "Bulk", "Container", "Conveyance"] },
        { label: "Name of Vessel", id: "vesselName", type: "text" },
        { label: "Voyage Start Date", id: "voyageStartDate", type: "date" },
        { label: "Voyage End Date", id: "voyageEndDate", type: "date" },
        { label: "Port of Loading", id: "portOfLoading", type: "text" },
        { label: "Port of Discharge", id: "portOfDischarge", type: "text" },
        { label: "Final Destination", id: "finalDestination", type: "text" },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I declare that the above information is true and complete, and that I have withheld no material information regarding this proposal."] },
    ],
    "Motor Insurance Application Form": [
        { label: "Full Customer Name", id: "customerName", type: "text", required: true },
        { label: "Address", id: "address", type: "text", required: true },
        { label: "P.O. Box", id: "poBox", type: "text" },
        { label: "Code", id: "code", type: "text" },
        { label: "Tel", id: "tel", type: "text" },
        { label: "E-mail", id: "email", type: "email" },
        { label: "Mobile No.", id: "mobileNo", type: "text" },
        { label: "Policy Period From", id: "policyFrom", type: "date" },
        { label: "Policy Period To", id: "policyTo", type: "date" },
        { label: "Registration Marks (Number Plate)", id: "registrationMarks", type: "text" },
        { label: "Make of Vehicle", id: "makeOfVehicle", type: "text" },
        { label: "Chassis Number", id: "chassisNumber", type: "text" },
        { label: "Engine Number", id: "engineNumber", type: "text" },
        { label: "Type of Body", id: "typeOfBody", type: "text" },
        { label: "Cubic Capacity", id: "cubicCapacity", type: "text" },
        { label: "Seating Capacity", id: "seatingCapacity", type: "text" },
        { label: "Sum Insured (KES)", id: "sumInsured", type: "number" },
        { label: "Scope of Cover", id: "scopeOfCover", type: "checkboxes", options: ["Comprehensive", "Third Party Only"] },
        { label: "Other Cover Extensions", id: "otherCoverExtensions", type: "checkboxes", options: ["Material Damage Excess Protector", "Theft Excess Protector", "Political Violence and Terrorism (PVT)", "Courtesy Car", "AA Membership", "Others"] },
        { label: "Use of the Vehicle", id: "useOfVehicle", type: "checkboxes", options: ["Private Own Use", "Commercial General Cartage", "Commercial Own Goods", "PSV Matatu", "PSV Motorcycle", "Taxi / Private Hire Self Drive", "Private Hire (Chauffer Driven)", "Tours", "Uber", "Institutional Vehicle", "Hearse", "Oil Tanker", "Others"] },
        { label: "Names of Authorized Drivers", id: "authorizedDrivers", type: "textarea" },
        { label: "Declaration Name of Applicant", id: "declarationName", type: "text", required: true },
        { label: "Signature", id: "signature", type: "text", required: true },
        { label: "ID No.", id: "idNo", type: "text" },
        { label: "PIN Number", id: "pinNumber", type: "text" },
        { label: "Issued By (Galloways Staff)", id: "issuedBy", type: "text" },
        { label: "Mode of Payment", id: "modeOfPayment", type: "text" },
    ],
    "Political Violence Proposal": [
        { label: "Proposer and all subsidiary companies", id: "proposerSubsidiaries", type: "text", required: true },
        { label: "Proposer mailing address", id: "proposerAddress", type: "text", required: true },
        { label: "Nationality & Date established", id: "nationalityDate", type: "text" },
        { label: "Status of proposer", id: "proposerStatus", type: "select", options: ["Private Company", "Public Company", "Government Owned", "Other"] },
        { label: "Proposer's shareholding (%)", id: "proposerShareholding", type: "text" },
        { label: "Other Shareholders' Percentage & Nationality", id: "otherShareholders", type: "textarea" },
        { label: "Business operation description", id: "businessDescription", type: "textarea" },
        { label: "Policy currency to be used", id: "policyCurrency", type: "select", options: ["KES", "USD", "GBP", "EUR"] },
        { label: "Coverage Required", id: "coverageRequired", type: "checkboxes", options: ["Sabotage & Terrorism", "SRCC & Malicious Damage", "Full Political Violence"] },
        { label: "Physical Assets and Business Interruption values at locations", id: "assetValues", type: "table", columns: ["Buildings", "Contents", "Business Interruption", "Total Asset Values"] },
        { label: "Limit of Liability requested for Buildings, Contents, Business Interruption (Each Loss)", id: "liabilityLimitsEachLoss", type: "table", columns: ["Building", "Contents", "Business Interruption", "Total Each Loss"] },
        { label: "Limit of Liability requested (Total Each Policy)", id: "liabilityLimitsTotalPolicy", type: "text" },
        { label: "Details of all security arrangements & public access", id: "securityArrangements", type: "textarea" },
        { label: "Details of any public parking (including street parking)", id: "publicParking", type: "textarea" },
        { label: "Details of area surrounding location(s)", id: "areaSurroundings", type: "textarea" },
        { label: "Details of landmark buildings, government offices, hotels, etc. within 500m", id: "landmarksNearby", type: "textarea" },
        { label: "Describe occupants of surrounding buildings and their occupation", id: "surroundingOccupants", type: "textarea" },
        { label: "Details of any direct/indirect threat made against proposer/shareholders", id: "threatDetails", type: "textarea" },
        { label: "Details of previous acts of Terrorism, Sabotage, SRCC, Malicious Damage, War, etc.", id: "previousActs", type: "textarea" },
        { label: "Reason for requesting terrorism cover", id: "reasonTerrorismCover", type: "textarea" },
        { label: "Description of security at location(s)", id: "securityDescription", type: "textarea" },
        { label: "Business involvement with government agencies", id: "govtBusinessInvolvement", type: "textarea" },
        { label: "Premises owned/leased/rented to government/state agency", id: "govtPremises", type: "textarea" },
        { label: "Vicinity of government premises/sites", id: "vicinityGovtPremises", type: "checkboxes", options: ["Government premises/sites", "Major economic centres", "Major tourist attractions", "Major sporting stadia", "International airports"] },
        { label: "Period of cover required", id: "periodOfCover", type: "text" },
        { label: "Are any assets already covered against terrorism?", id: "assetsAlreadyCovered", type: "select", options: ["Yes", "No"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I declare the statements are true, complete and correct."] },
        { label: "Privacy Statement & Consent (Galloways)", id: "privacyConsent", type: "checkbox", options: ["I have read and agree to Galloways Privacy Statement."] },
        { label: "Consent for processing Personal Data relating to a child", id: "childConsent", type: "select", options: ["I AGREE", "I DO NOT AGREE", "Not Applicable"] },
        { label: "Consent for transfer outside Kenya", id: "transferConsent", type: "select", options: ["I AGREE", "I DO NOT AGREE"] },
        { label: "Marketing consent", id: "marketingConsent", type: "select", options: ["YES", "NO"] },
        { label: "Signature", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Contractors Plant and Machinery": [
        { label: "Proposer Name", id: "proposerName", type: "text", required: true },
        { label: "Proposer Address", id: "proposerAddress", type: "text", required: true },
        { label: "Insurance Period (months/years)", id: "insurancePeriod", type: "text" },
        { label: "Commencement Date", id: "commencementDate", type: "date" },
        { label: "Geographical Scope of Cover", id: "geoScope", type: "text" },
        { label: "Previous CPM Insurance?", id: "previousCPM", type: "select", options: ["Yes", "No"] },
        { label: "Previous CPM Details", id: "previousCPMDetails", type: "textarea" },
        { label: "Hired Plant/Machinery?", id: "hiredPlant", type: "select", options: ["Yes", "No"] },
        { label: "Owner's Name & Address (if hired)", id: "ownerDetails", type: "text" },
        { label: "Exposure to Hazards", id: "hazards", type: "checkboxes", options: ["Fire/Explosion", "Earthquake/Volcanic/Tsunami", "Employment Underground", "Storm/Cyclone", "Flood/Inundation", "Employment in Mountain Terrain", "Landslide", "Blasting", "Other"] },
        { label: "Extra Charges Cover (Overtime, night work, holidays)", id: "extraChargesCover", type: "select", options: ["Yes", "No"] },
        { label: "Limit of Indemnity for Extra Charges", id: "extraChargesLimit", type: "text" },
        { label: "Inland Transport Cover?", id: "inlandTransport", type: "select", options: ["Yes", "No"] },
        { label: "Maximum Value Transported by One Means", id: "maxTransportValue", type: "text" },
        { label: "Consent for Marketing Purposes", id: "marketingConsent", type: "select", options: ["I consent", "I do not consent"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I declare the statements are true and complete."] },
        { label: "Privacy Notice Consent", id: "privacyConsent", type: "checkbox", options: ["I have read and understood the Privacy Notice."] },
        { label: "Executed at", id: "executedAt", type: "text" },
        { label: "Date", id: "date", type: "date", required: true },
        { label: "Signature", id: "signature", type: "text", required: true },
        { label: "Schedule of Items (table)", id: "scheduleItems", type: "table", columns: ["Item No.", "Description", "Year of Manufacture", "Hazards", "Replacement Value", "Manufacturer", "Type/Serial No.", "Output"] },
    ],
    "Carriers Legal Liability Insurance": [
        { label: "Name of Proposer", id: "proposerName", type: "text", required: true },
        { label: "Address and Contacts", id: "proposerAddress", type: "text", required: true },
        { label: "Pin Certificate Number", id: "pinCertificate", type: "text" },
        { label: "Physical Address of Central Office", id: "centralOfficeAddress", type: "text" },
        { label: "Business Type (Sole Trader, Partnership, Limited Company)", id: "businessType", type: "select", options: ["Sole Trader", "Partnership", "Limited Company"] },
        { label: "Business/Occupation Description", id: "businessDescription", type: "textarea" },
        { label: "Date of Business Registration", id: "businessRegistrationDate", type: "date" },
        { label: "Ownership Change Since Registration?", id: "ownershipChange", type: "select", options: ["Yes", "No"] },
        { label: "Ownership Change Details", id: "ownershipChangeDetails", type: "textarea" },
        { label: "Main Types of Goods Carried/Handled/Warehoused", id: "goodsTypes", type: "textarea" },
        { label: "Area of Operations (Geographical)", id: "areaOfOperations", type: "text" },
        { label: "Vehicles Owned/Hired", id: "vehiclesOwnedHired", type: "select", options: ["Owned", "Hired", "Owned and Hired"] },
        { label: "Subcontract Carriage?", id: "subcontractCarriage", type: "select", options: ["Yes", "No"] },
        { label: "Written Contracts with Subcontractors?", id: "writtenContracts", type: "select", options: ["Yes", "No"] },
        { label: "Subcontractor Contract Details", id: "subcontractorDetails", type: "textarea" },
        { label: "Vehicle Register Maintained?", id: "vehicleRegister", type: "select", options: ["Yes", "No"] },
        { label: "Vehicle Register Details", id: "vehicleRegisterDetails", type: "textarea" },
        { label: "Vehicle Maintenance Details", id: "vehicleMaintenance", type: "textarea" },
        { label: "Hired Vehicle Maintenance & Staff Reliability", id: "hiredVehicleMaintenance", type: "textarea" },
        { label: "Goods Safety During Temporary Garaging", id: "goodsSafety", type: "textarea" },
        { label: "Vehicle Security Devices", id: "securityDevices", type: "checkboxes", options: ["Tracking Devices", "Radio Communication", "Engine Immobilizers", "Overloading Devices", "Other"] },
        { label: "Total Number of Own Employees", id: "ownEmployees", type: "number" },
        { label: "Total Number of Hired Drivers/Operators", id: "hiredDrivers", type: "number" },
        { label: "Employee Vetting System", id: "employeeVetting", type: "textarea" },
        { label: "Driver License & Identity Verification", id: "driverVerification", type: "textarea" },
        { label: "Limits of Liability Required (table)", id: "liabilityLimits", type: "table", columns: ["Any One Claim (KES)", "All Claims One Event (KES)", "All Claims Period of Insurance (KES)"] },
        { label: "Estimated Annual Carry (KES)", id: "estimatedAnnualCarry", type: "number" },
        { label: "Actual Annual Carry (last 3 years)", id: "actualAnnualCarry", type: "table", columns: ["Year", "KES"] },
        { label: "Insurance/Loss History", id: "insuranceLossHistory", type: "textarea" },
        { label: "Previous Loss Details (last 3 years)", id: "previousLossDetails", type: "textarea" },
        { label: "Precautions to Avoid Recurrence", id: "precautionsRecurrence", type: "textarea" },
        { label: "Insurance Company History (Cancelled, Declined, etc.)", id: "insuranceCompanyHistory", type: "checkboxes", options: ["Cancelled Policy", "Declined to Insure", "Declined to Renew", "Imposed Special Terms", "Declined Claim"] },
        { label: "Insurance Company History Details", id: "insuranceCompanyHistoryDetails", type: "textarea" },
        { label: "Consent for Data Processing", id: "dataConsent", type: "select", options: ["YES", "NO"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I declare the answers are true and complete."] },
        { label: "Signature", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Public Liability": [
        { label: "Name of Proposer (in full)", id: "proposerName", type: "text", required: true },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number(s)", id: "telephoneNumbers", type: "text" },
        { label: "Email Address", id: "emailAddress", type: "text" },
        { label: "ID Number (if applicable)", id: "idNumber", type: "text" },
        { label: "PIN No.", id: "pinNo", type: "text" },
        { label: "Period of Insurance (From/To)", id: "periodOfInsurance", type: "text" },
        { label: "Limits of Liability Required (table)", id: "liabilityLimits", type: "table", columns: ["Any One Claim (KES)", "All Claims One Event (KES)", "All Claims Period of Insurance (KES)"] },
        { label: "Full Description of Business/Trade/Occupation", id: "businessDescription", type: "textarea" },
        { label: "Hotel/Club Seating Capacity", id: "seatingCapacity", type: "number" },
        { label: "Accommodation Facilities Offered?", id: "accommodationFacilities", type: "select", options: ["Yes", "No"] },
        { label: "Car Park Facilities Provided?", id: "carParkFacilities", type: "select", options: ["Yes", "No"] },
        { label: "Premises Description & Physical Address", id: "premisesDescription", type: "textarea" },
        { label: "Do you own the premises?", id: "ownPremises", type: "select", options: ["Yes", "No"] },
        { label: "Are you the sole occupier?", id: "soleOccupier", type: "select", options: ["Yes", "No"] },
        { label: "Are premises, plant and machinery in sound state?", id: "soundState", type: "select", options: ["Yes", "No"] },
        { label: "Use of acids, gases, chemicals, explosives, radioactive substances?", id: "hazardousMaterials", type: "select", options: ["Yes", "No"] },
        { label: "Hazardous Materials Details", id: "hazardousMaterialsDetails", type: "textarea" },
        { label: "Extend cover to lifts, cranes, hoists, lifting apparatus?", id: "liftingApparatus", type: "select", options: ["Yes", "No"] },
        { label: "Property belonging to customers left in premises?", id: "customerProperty", type: "select", options: ["Yes", "No"] },
        { label: "Business activities entail working away from premises?", id: "workAwayPremises", type: "select", options: ["Yes", "No"] },
        { label: "Other work site locations", id: "otherWorkSites", type: "text" },
        { label: "Cover liability for guests' personal effects?", id: "guestsPersonalEffects", type: "select", options: ["Yes", "No"] },
        { label: "Indemnity Limit for Guests' Personal Effects", id: "guestsIndemnityLimit", type: "text" },
        { label: "Insurance Claims History", id: "claimsHistory", type: "textarea" },
        { label: "Currently insured for this type of risk?", id: "currentlyInsured", type: "select", options: ["Yes", "No"] },
        { label: "Previously insured for this type of insurance?", id: "previouslyInsured", type: "select", options: ["Yes", "No"] },
        { label: "Previous Insurer & Policy Number", id: "previousInsurer", type: "text" },
        { label: "Previous loss details", id: "previousLossDetails", type: "textarea" },
        { label: "Insurance Company History (Cancelled, Declined, etc.)", id: "insuranceCompanyHistory", type: "checkboxes", options: ["Cancelled Policy", "Declined to Insure", "Declined to Renew", "Imposed Special Terms", "Repudiated Claim"] },
        { label: "Insurance Company History Details", id: "insuranceCompanyHistoryDetails", type: "textarea" },
        { label: "Consent for Data Processing", id: "dataConsent", type: "select", options: ["YES", "NO"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I declare the answers are true and complete."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Professional Indemnity Proposal Form (General)": [
        { label: "Name of Insured", id: "nameInsured", type: "text", required: true },
        { label: "Practice Title", id: "practiceTitle", type: "text" },
        { label: "Address", id: "address", type: "text" },
        { label: "Legal Constitution", id: "legalConstitution", type: "select", options: ["Partnership", "Incorporated Company", "Limited Company", "Close Corporation", "Sole Practitioner"] },
        { label: "Date of Commencement", id: "dateCommencement", type: "date" },
        { label: "Discipline(s) Engaged", id: "disciplines", type: "text" },
        { label: "Principals/Partners/Directors", id: "principals", type: "textarea" },
        { label: "Claims History", id: "claimsHistory", type: "textarea" },
        { label: "Indemnity Limit", id: "indemnityLimit", type: "number" },
        { label: "Fee Income (last 3 years)", id: "feeIncome", type: "table", columns: ["Year", "Gross Fees"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I declare the statements are true and complete."] },
        { label: "Privacy Statement & Consent (Galloways)", id: "privacyConsent", type: "checkbox", options: ["I have read and agree to Galloways Privacy Statement."] },
        { label: "Signature", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Professional Indemnity Proposal Form (Engineers/Architects)": [
        { label: "Title of Insured / Practice", id: "practiceTitle", type: "text", required: true },
        { label: "P.O. Box", id: "poBox", type: "text" },
        { label: "Postal Code", id: "postalCode", type: "text" },
        { label: "Town", id: "town", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Fax Number", id: "fax", type: "text" },
        { label: "Mobile Number", id: "mobile", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "VAT Registration Number", id: "vatReg", type: "text" },
        { label: "PIN Number", id: "pin", type: "text" },
        { label: "Legal Constitution", id: "legalConstitution", type: "select", options: ["Partnership", "Incorporated Company", "Limited Company", "Close Corporation", "Sole Practitioner"] },
        { label: "Principal Office Address", id: "principalOffice", type: "text" },
        { label: "Subsidiary Office Address", id: "subsidiaryOffice", type: "text" },
        { label: "Date of Commencement (Current)", id: "dateCommencementCurrent", type: "date" },
        { label: "Date of Commencement (Initial)", id: "dateCommencementInitial", type: "date" },
        { label: "Disciplines Engaged In", id: "disciplines", type: "textarea" },
        { label: "Names and Qualifications of Principals", id: "principals", type: "textarea" },
        { label: "Claims History", id: "claimsHistory", type: "select", options: ["Yes", "No"] },
        { label: "Claims Details (if Yes)", id: "claimsDetails", type: "textarea" },
        { label: "Awareness of Circumstances for Claims", id: "awarenessCircumstances", type: "select", options: ["Yes", "No"] },
        { label: "Circumstances Details (if Yes)", id: "circumstancesDetails", type: "textarea" },
        { label: "Present/Past Insurance", id: "pastInsurance", type: "select", options: ["Yes", "No"] },
        { label: "Past Insurance Details", id: "pastInsuranceDetails", type: "textarea" },
        { label: "Indemnity for Retired/Left Principals", id: "indemnityRetired", type: "select", options: ["Yes", "No"] },
        { label: "Retired Principal Details", id: "retiredPrincipalDetails", type: "textarea" },
        { label: "Declined/Cancelled/Terms Imposed by Insurer", id: "declinedTerms", type: "select", options: ["Yes", "No"] },
        { label: "Declined/Terms Details", id: "declinedTermsDetails", type: "textarea" },
        { label: "Liability for Undiscovered Claims (Run-Off)", id: "runOffLiability", type: "select", options: ["Yes", "No"] },
        { label: "Total Number of Staff", id: "staffTotal", type: "number" },
        { label: "Staff Breakdown", id: "staffBreakdown", type: "textarea" },
        { label: "Percentage of Briefs by Type", id: "briefsPercentage", type: "textarea" },
        { label: "Percentage of Work Location (Chambers/Court)", id: "workLocationPercentage", type: "textarea" },
        { label: "Indemnity Limits Required", id: "indemnityLimits", type: "textarea" },
        { label: "Fee Income (Last 3 Years)", id: "feeIncomeHistory", type: "textarea" },
        { label: "Estimated Fee Income (Next 12 Months)", id: "feeIncomeEstimate", type: "number" },
        { label: "Extensions to Basic Cover", id: "extensionsBasicCover", type: "checkboxes", options: ["Loss of Documents", "Dishonesty of Employees", "Libel and Slander"] },
        { label: "Extension Limits", id: "extensionLimits", type: "textarea" },
        { label: "Consent for Data Processing", id: "consentData", type: "select", options: ["Yes", "No"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I/We declare that the above statements and particulars are true and complete."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Professional Indemnity Insurance Proposal Form (Medical Practitioners)": [
        { label: "Full Name", id: "fullName", type: "text", required: true },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Business Address", id: "businessAddress", type: "text" },
        { label: "Medical School Graduated From", id: "medicalSchool", type: "text" },
        { label: "Year of Graduation", id: "yearGraduation", type: "number" },
        { label: "Other Medical Schools Attended", id: "otherMedicalSchools", type: "text" },
        { label: "Year of Graduation (Other)", id: "yearGraduationOther", type: "number" },
        { label: "Practice History Since Graduation", id: "practiceHistory", type: "textarea" },
        { label: "Licensed to Practice at Address?", id: "licensed", type: "select", options: ["Yes", "No"] },
        { label: "Association Memberships", id: "associationMemberships", type: "textarea" },
        { label: "Nature of Present/Future Activities", id: "natureActivities", type: "checkboxes", options: ["Physician", "Surgeon", "Cosmetic Surgeon", "Anaesthetist", "Gynaecologist", "Urologist", "Orthopaedist", "Radiologist", "Dentist", "Other"] },
        { label: "Regular First-Aid Service?", id: "firstAidService", type: "select", options: ["Yes", "No"] },
        { label: "Partners (Names)", id: "partners", type: "textarea" },
        { label: "Qualified Medical Assistants (Names)", id: "medicalAssistants", type: "textarea" },
        { label: "Number of Technicians", id: "technicians", type: "number" },
        { label: "Number of Nurses", id: "nurses", type: "number" },
        { label: "Contracted/Employed by Firm/Co?", id: "contractedFirm", type: "select", options: ["Yes", "No"] },
        { label: "Own/Operate Hospital/Clinic?", id: "ownHospital", type: "select", options: ["Yes", "No"] },
        { label: "Hospital/Clinic Details", id: "hospitalDetails", type: "textarea" },
        { label: "Own/Operate X-ray/Laser?", id: "ownXrayLaser", type: "select", options: ["Yes", "No"] },
        { label: "X-ray/Laser Details", id: "xrayLaserDetails", type: "textarea" },
        { label: "Number of Patients per Year", id: "patientsPerYear", type: "number" },
        { label: "Previous Insurance?", id: "previousInsurance", type: "select", options: ["Yes", "No"] },
        { label: "Previous Insurance Details", id: "previousInsuranceDetails", type: "textarea" },
        { label: "Previous Application Declined?", id: "applicationDeclined", type: "select", options: ["Yes", "No"] },
        { label: "Special Restrictions/Terminated Insurance?", id: "specialRestrictions", type: "select", options: ["Yes", "No"] },
        { label: "Claims/Suits for Malpractice (Last 5 Years)?", id: "malpracticeClaims", type: "select", options: ["Yes", "No"] },
        { label: "Malpractice Claims Details", id: "malpracticeClaimsDetails", type: "textarea" },
        { label: "Awareness of Circumstances for Claims?", id: "awarenessClaims", type: "select", options: ["Yes", "No"] },
        { label: "Circumstances Details", id: "circumstancesDetails", type: "textarea" },
        { label: "Indemnity Required (Any One Claim)", id: "indemnityOneClaim", type: "number" },
        { label: "Indemnity Required (Annual Aggregate)", id: "indemnityAggregate", type: "number" },
        { label: "Deductible Per Claim", id: "deductible", type: "number" },
        { label: "Consent for Data Processing", id: "consentData", type: "select", options: ["Yes", "No"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I/We declare that the statements and particulars are true and complete."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Professional Indemnity Insurance Proposal Form (Accountants/Auditors)": [
        { label: "Title of Insured / Practice", id: "practiceTitle", type: "text", required: true },
        { label: "P.O. Box", id: "poBox", type: "text" },
        { label: "Postal Code", id: "postalCode", type: "text" },
        { label: "Town", id: "town", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Fax Number", id: "fax", type: "text" },
        { label: "Mobile Number", id: "mobile", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "VAT Registration Number", id: "vatReg", type: "text" },
        { label: "PIN Number", id: "pin", type: "text" },
        { label: "Legal Constitution", id: "legalConstitution", type: "select", options: ["Partnership", "Incorporated Company", "Limited Company", "Close Corporation", "Sole Practitioner"] },
        { label: "Principal Office Address", id: "principalOffice", type: "text" },
        { label: "Subsidiary Office Address", id: "subsidiaryOffice", type: "text" },
        { label: "Date of Commencement (Current)", id: "dateCommencementCurrent", type: "date" },
        { label: "Date of Commencement (Initial)", id: "dateCommencementInitial", type: "date" },
        { label: "Disciplines Engaged In", id: "disciplines", type: "textarea" },
        { label: "Names and Qualifications of Principals", id: "principals", type: "textarea" },
        { label: "Claims History", id: "claimsHistory", type: "select", options: ["Yes", "No"] },
        { label: "Claims Details (if Yes)", id: "claimsDetails", type: "textarea" },
        { label: "Awareness of Circumstances for Claims", id: "awarenessCircumstances", type: "select", options: ["Yes", "No"] },
        { label: "Circumstances Details (if Yes)", id: "circumstancesDetails", type: "textarea" },
        { label: "Present/Past Insurance", id: "pastInsurance", type: "select", options: ["Yes", "No"] },
        { label: "Past Insurance Details", id: "pastInsuranceDetails", type: "textarea" },
        { label: "Indemnity for Retired/Left Principals", id: "indemnityRetired", type: "select", options: ["Yes", "No"] },
        { label: "Retired Principal Details", id: "retiredPrincipalDetails", type: "textarea" },
        { label: "Declined/Cancelled/Terms Imposed by Insurer", id: "declinedTerms", type: "select", options: ["Yes", "No"] },
        { label: "Declined/Terms Details", id: "declinedTermsDetails", type: "textarea" },
        { label: "Liability for Undiscovered Claims (Run-Off)", id: "runOffLiability", type: "select", options: ["Yes", "No"] },
        { label: "Total Number of Staff", id: "staffTotal", type: "number" },
        { label: "Staff Breakdown", id: "staffBreakdown", type: "textarea" },
        { label: "Percentage of Briefs by Type", id: "briefsPercentage", type: "textarea" },
        { label: "Percentage of Work Location (Chambers/Court)", id: "workLocationPercentage", type: "textarea" },
        { label: "Indemnity Limits Required", id: "indemnityLimits", type: "textarea" },
        { label: "Fee Income (Last 3 Years)", id: "feeIncomeHistory", type: "textarea" },
        { label: "Estimated Fee Income (Next 12 Months)", id: "feeIncomeEstimate", type: "number" },
        { label: "Extensions to Basic Cover", id: "extensionsBasicCover", type: "checkboxes", options: ["Loss of Documents", "Dishonesty of Employees", "Libel and Slander"] },
        { label: "Extension Limits", id: "extensionLimits", type: "textarea" },
        { label: "Consent for Data Processing", id: "consentData", type: "select", options: ["Yes", "No"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I/We declare that the above statements and particulars are true and complete."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Professional Indemnity Insurance Proposal Form (Lawyers/Advocates)": [
        { label: "Title of Insured / Practice", id: "practiceTitle", type: "text", required: true },
        { label: "P.O. Box", id: "poBox", type: "text" },
        { label: "Postal Code", id: "postalCode", type: "text" },
        { label: "Town", id: "town", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Fax Number", id: "fax", type: "text" },
        { label: "Mobile Number", id: "mobile", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "VAT Registration Number", id: "vatReg", type: "text" },
        { label: "PIN Number", id: "pin", type: "text" },
        { label: "Legal Constitution", id: "legalConstitution", type: "select", options: ["Partnership", "Incorporated Company", "Limited Company", "Close Corporation", "Sole Practitioner"] },
        { label: "Principal Office Address", id: "principalOffice", type: "text" },
        { label: "Subsidiary Office Address", id: "subsidiaryOffice", type: "text" },
        { label: "Date of Commencement (Current)", id: "dateCommencementCurrent", type: "date" },
        { label: "Date of Commencement (Initial)", id: "dateCommencementInitial", type: "date" },
        { label: "Disciplines Engaged In", id: "disciplines", type: "textarea" },
        { label: "Names and Qualifications of Principals", id: "principals", type: "textarea" },
        { label: "Claims History", id: "claimsHistory", type: "select", options: ["Yes", "No"] },
        { label: "Claims Details (if Yes)", id: "claimsDetails", type: "textarea" },
        { label: "Awareness of Circumstances for Claims", id: "awarenessCircumstances", type: "select", options: ["Yes", "No"] },
        { label: "Circumstances Details (if Yes)", id: "circumstancesDetails", type: "textarea" },
        { label: "Present/Past Insurance", id: "pastInsurance", type: "select", options: ["Yes", "No"] },
        { label: "Past Insurance Details", id: "pastInsuranceDetails", type: "textarea" },
        { label: "Indemnity for Retired/Left Principals", id: "indemnityRetired", type: "select", options: ["Yes", "No"] },
        { label: "Retired Principal Details", id: "retiredPrincipalDetails", type: "textarea" },
        { label: "Declined/Cancelled/Terms Imposed by Insurer", id: "declinedTerms", type: "select", options: ["Yes", "No"] },
        { label: "Declined/Terms Details", id: "declinedTermsDetails", type: "textarea" },
        { label: "Liability for Undiscovered Claims (Run-Off)", id: "runOffLiability", type: "select", options: ["Yes", "No"] },
        { label: "Total Number of Staff", id: "staffTotal", type: "number" },
        { label: "Staff Breakdown", id: "staffBreakdown", type: "textarea" },
        { label: "Percentage of Briefs by Type", id: "briefsPercentage", type: "textarea" },
        { label: "Percentage of Work Location (Chambers/Court)", id: "workLocationPercentage", type: "textarea" },
        { label: "Indemnity Limits Required", id: "indemnityLimits", type: "textarea" },
        { label: "Fee Income (Last 3 Years)", id: "feeIncomeHistory", type: "textarea" },
        { label: "Estimated Fee Income (Next 12 Months)", id: "feeIncomeEstimate", type: "number" },
        { label: "Extensions to Basic Cover", id: "extensionsBasicCover", type: "checkboxes", options: ["Loss of Documents", "Dishonesty of Employees", "Libel and Slander"] },
        { label: "Extension Limits", id: "extensionLimits", type: "textarea" },
        { label: "Consent for Data Processing", id: "consentData", type: "select", options: ["Yes", "No"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I/We declare that the above statements and particulars are true and complete."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Machinery Breakdown/Damage": [
        { label: "Name of Insured", id: "insuredName", type: "text", required: true },
        { label: "Address of Insured", id: "insuredAddress", type: "text" },
        { label: "Location of Damage", id: "damageLocation", type: "text" },
        { label: "Policy Number", id: "policyNumber", type: "text" },
        { label: "Identification Number and Description of Item Damaged", id: "itemDescription", type: "textarea" },
        { label: "Date of Accident", id: "accidentDate", type: "date" },
        { label: "Cause and Full Description of Circumstances of Accident", id: "accidentDescription", type: "textarea" },
        { label: "Repairs/Replacement Necessary and Estimated Cost", id: "repairsEstimate", type: "textarea" },
        { label: "Repairs Put in Hand or Completed? By Whom?", id: "repairsByWhom", type: "textarea" },
        { label: "Where Can Damaged Parts Be Inspected?", id: "inspectionLocation", type: "text" },
        { label: "Accident Caused by Third Party?", id: "thirdParty", type: "select", options: ["Yes", "No"] },
        { label: "Third Party Name and Address", id: "thirdPartyDetails", type: "textarea" },
        { label: "Claim Made Upon Third Party?", id: "claimThirdParty", type: "select", options: ["Yes", "No"] },
        { label: "Third Party Correspondence Details", id: "thirdPartyCorrespondence", type: "textarea" },
        { label: "Who Witnessed the Accident?", id: "witnesses", type: "textarea" },
        { label: "Other Insurance Entitled to Recover for Damage?", id: "otherInsurance", type: "select", options: ["Yes", "No"] },
        { label: "Other Insurance Details", id: "otherInsuranceDetails", type: "textarea" },
        { label: "Remarks", id: "remarks", type: "textarea" },
        { label: "Consent for Data Processing", id: "consentData", type: "select", options: ["Yes", "No"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I/We declare that the foregoing particulars are true and correct."] },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Equimed Application Form (Medical Insurance)": [
        { label: "Principal Applicant Name", id: "principalName", type: "text", required: true },
        { label: "National ID/Passport No.", id: "principalId", type: "text" },
        { label: "NHIF Member No.", id: "nhifNo", type: "text" },
        { label: "KRA Pin No.", id: "kraPin", type: "text" },
        { label: "Date of Birth", id: "dob", type: "date" },
        { label: "Occupation", id: "occupation", type: "text" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Mobile Number", id: "mobile", type: "tel" },
        { label: "Postal Address & Code", id: "postalAddress", type: "text" },
        { label: "Physical Address/Residence", id: "physicalAddress", type: "text" },
        { label: "Next of Kin Name & ID No.", id: "nextOfKin", type: "text" },
        { label: "Height (cm)", id: "height", type: "number" },
        { label: "Weight (kg)", id: "weight", type: "number" },
        { label: "Nomination of Beneficiary Name", id: "beneficiaryName", type: "text" },
        { label: "Beneficiary ID Number", id: "beneficiaryId", type: "text" },
        { label: "Beneficiary Mobile Number", id: "beneficiaryMobile", type: "tel" },
        { label: "Beneficiary Relationship", id: "beneficiaryRelationship", type: "text" },
        { label: "Dependants (Name, DOB, Gender, Relationship, ID, Weight, Height)", id: "dependants", type: "textarea" },
        { label: "Previous Scheme Membership Details", id: "previousScheme", type: "textarea" },
        { label: "Confidential Medical History", id: "medicalHistory", type: "textarea" },
        { label: "Exclusions Acknowledgement", id: "exclusions", type: "checkbox", options: ["I acknowledge the listed exclusions."] },
        { label: "Benefit(s) Selected", id: "benefitsSelected", type: "checkboxes", options: ["Inpatient", "Outpatient", "Dental", "Optical"] },
        { label: "Official Use (Premiums, Charges, Levies)", id: "officialUse", type: "textarea" },
        { label: "Consent for Data Processing", id: "consentData", type: "select", options: ["Yes", "No"] },
        { label: "Declaration of Member", id: "declaration", type: "checkbox", options: ["I declare the information given is true and complete."] },
        { label: "Applicant's Signature", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Fire Insurance Proposal Form": [
        { label: "Full Name of Proposer", id: "fullName", type: "text", required: true },
        { label: "Business/Occupation", id: "businessOccupation", type: "text" },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Location of Property (Building/Street/Plot No./Town)", id: "propertyLocation", type: "text" },
        { label: "Type of Property", id: "propertyType", type: "select", options: ["Residential", "Commercial", "Industrial", "Other"] },
        { label: "Sum Insured (Ksh)", id: "sumInsured", type: "number" },
        { label: "Description of Property to be Insured", id: "propertyDescription", type: "textarea" },
        { label: "Construction Materials (Walls)", id: "wallsMaterial", type: "text" },
        { label: "Construction Materials (Roof)", id: "roofMaterial", type: "text" },
        { label: "Are there any hazardous materials stored?", id: "hazardousMaterials", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "hazardousDetails", type: "textarea" },
        { label: "Have you ever suffered loss/damage by fire?", id: "lossHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "lossDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Contractual Liability Proposal Form": [
        { label: "Full Name of Proposer/Organization", id: "proposerName", type: "text", required: true },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Nature of Business/Occupation", id: "businessNature", type: "text" },
        { label: "Type of Contract", id: "contractType", type: "text" },
        { label: "Contract Value (Ksh)", id: "contractValue", type: "number" },
        { label: "Period of Insurance (From)", id: "periodFrom", type: "date" },
        { label: "Period of Insurance (To)", id: "periodTo", type: "date" },
        { label: "Description of Works/Services", id: "worksDescription", type: "textarea" },
        { label: "Sum Insured (Ksh)", id: "sumInsured", type: "number" },
        { label: "Have you ever made a claim under contractual liability insurance?", id: "claimHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "claimDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer/Authorized Person", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Domestic Package Insurance": [
        { label: "Agency Name", id: "agencyName", type: "text" },
        { label: "Code", id: "agencyCode", type: "text" },
        { label: "PIN Number", id: "pinNumber", type: "text" },
        { label: "Name of Proposer (in full)", id: "proposerName", type: "text", required: true },
        { label: "Surname", id: "surname", type: "text" },
        { label: "First name", id: "firstName", type: "text" },
        { label: "Other names", id: "otherNames", type: "text" },
        { label: "Postal Address/Telephone", id: "postalAddress", type: "text" },
        { label: "Postal Code", id: "postalCode", type: "text" },
        { label: "Town", id: "town", type: "text" },
        { label: "ID Number/Passport/Business Reg. No", id: "idOrRegNo", type: "text" },
        { label: "Email Address", id: "emailAddress", type: "text" },
        { label: "Age (where applicable)", id: "age", type: "number" },
        { label: "Profession/Occupation", id: "occupation", type: "text" },
        { label: "Period of insurance (From/To)", id: "periodOfInsurance", type: "text" },
        { label: "Does any organization or individual have financial interest with your insured property(s)?", id: "financialInterest", type: "select", options: ["Yes", "No"] },
        { label: "If yes, briefly give details", id: "financialInterestDetails", type: "textarea" },
        { label: "Location of the premises: Building/Street/Road/Plot No./Town", id: "premisesLocation", type: "text" },
        { label: "Material of dwelling construction (Walls)", id: "wallsMaterial", type: "text" },
        { label: "Material of dwelling construction (Roofs)", id: "roofsMaterial", type: "text" },
        { label: "Will the dwelling be left without an inhabitant for more than 7 consecutive days?", id: "unoccupied7days", type: "select", options: ["Yes", "No"] },
        { label: "Extent (if yes)", id: "unoccupied7daysExtent", type: "text" },
        { label: "Will the dwelling be left without an inhabitant for more than 30 consecutive days?", id: "unoccupied30days", type: "select", options: ["Yes", "No"] },
        { label: "Extent (if yes)", id: "unoccupied30daysExtent", type: "text" },
        { label: "Do you wish to enhance the value of your building automatically at the end of every insurance period?", id: "enhanceValue", type: "select", options: ["Yes", "No"] },
        { label: "Percentage increase required", id: "valueIncrease", type: "select", options: ["5%", "10%", "15%", "20%", "Other"] },
        { label: "Other percentage (if selected)", id: "otherValueIncrease", type: "text" },
        { label: "Has any company or insurer declined to insure you?", id: "declinedToInsure", type: "select", options: ["Yes", "No"] },
        { label: "Required special terms to insure you?", id: "specialTerms", type: "select", options: ["Yes", "No"] },
        { label: "Cancelled or refused to renew your insurance?", id: "cancelledOrRefusedRenewal", type: "select", options: ["Yes", "No"] },
        { label: "Section A. Building - Sum Insured", id: "sectionABuildingSum", type: "number" },
        { label: "Section B. Contents - Sum Insured", id: "sectionBContentsSum", type: "number" },
        { label: "Section C. All Risk - Sum Insured", id: "sectionCAllRiskSum", type: "number" },
        { label: "List of items for All Risk (make, model, serial number)", id: "allRiskItems", type: "textarea" },
        { label: "Section D. Work Injury Benefits - Number of Workers", id: "sectionDWorkers", type: "number" },
        { label: "Section E. Owner's Liability - Limit", id: "sectionEOwnerLiabilityLimit", type: "number" },
        { label: "Section F. Occupier's and Personal Liability - Limit", id: "sectionFOccupierLiabilityLimit", type: "number" },
        { label: "Additional Benefits (ATM withdrawal, freezer contents, emergency rescue)", id: "additionalBenefits", type: "checkboxes", options: ["ATM withdrawal (up to 20,000)", "Freezer contents (up to 5,000)", "Emergency rescue/fire fighting (up to 50,000)"] },
        { label: "Credit Reference Bureau consent", id: "creditReferenceConsent", type: "checkbox", options: ["I confirm authorization to share/access credit information."] },
        { label: "Premium Payment consent", id: "premiumPaymentConsent", type: "checkbox", options: ["I confirm all premiums will be paid directly to Madison General Insurance Kenya Limited."] },
        { label: "Privacy Statement & Consent (Galloways)", id: "privacyConsent", type: "checkbox", options: ["I have read and agree to Galloways Privacy Statement."] },
        { label: "Consent for processing Personal Data relating to a child", id: "childConsent", type: "select", options: ["I AGREE", "I DO NOT AGREE", "Not Applicable"] },
        { label: "Consent for transfer outside Kenya", id: "transferConsent", type: "select", options: ["I AGREE", "I DO NOT AGREE"] },
        { label: "Marketing consent", id: "marketingConsent", type: "select", options: ["YES", "NO"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I acknowledge I have read and understood the privacy statement and selected my choices freely."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Goods in Transit Insurance": [
        { label: "Full Name of Proposer", id: "fullName", type: "text", required: true },
        { label: "Business/Occupation", id: "businessOccupation", type: "text" },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Nature of Goods to be Insured", id: "goodsNature", type: "textarea" },
        { label: "Sum Insured (Ksh)", id: "sumInsured", type: "number" },
        { label: "Estimated Annual Carryings (Ksh)", id: "annualCarryings", type: "number" },
        { label: "Type of Conveyance", id: "conveyanceType", type: "select", options: ["Own Vehicles", "Hired Vehicles", "Rail", "Other"] },
        { label: "Number of Vehicles", id: "vehicleCount", type: "number" },
        { label: "Vehicle Registration Numbers", id: "vehicleRegNumbers", type: "textarea" },
        { label: "Territorial Limits (where goods will be carried)", id: "territorialLimits", type: "text" },
        { label: "Have you ever suffered loss/damage in transit?", id: "lossHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "lossDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Money Insurance": [
        { label: "Full Name of Proposer", id: "fullName", type: "text", required: true },
        { label: "Business/Occupation", id: "businessOccupation", type: "text" },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Type of Money to be Insured", id: "moneyType", type: "select", options: ["Cash", "Cheques", "Postal Orders", "Other"] },
        { label: "Sum Insured (Ksh)", id: "sumInsured", type: "number" },
        { label: "Estimated Annual Carryings (Ksh)", id: "annualCarryings", type: "number" },
        { label: "Means of Conveyance", id: "conveyanceMeans", type: "select", options: ["Own Employees", "Security Company", "Other"] },
        { label: "Number of Employees Involved", id: "employeeCount", type: "number" },
        { label: "Details of Security Arrangements", id: "securityDetails", type: "textarea" },
        { label: "Territorial Limits (where money will be carried)", id: "territorialLimits", type: "text" },
        { label: "Have you ever suffered loss/damage of money?", id: "lossHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "lossDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Group Personal Accident Proposal Form": [
        { label: "Name of Proposer/Organization", id: "proposerName", type: "text", required: true },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Nature of Business/Occupation", id: "businessNature", type: "text" },
        { label: "Number of Persons to be Insured", id: "personCount", type: "number" },
        { label: "List of Persons (Name, Age, Occupation)", id: "personList", type: "textarea" },
        { label: "Period of Insurance (From)", id: "periodFrom", type: "date" },
        { label: "Period of Insurance (To)", id: "periodTo", type: "date" },
        { label: "Benefits Required (Death, Permanent Disability, Medical Expenses, etc.)", id: "benefitsRequired", type: "checkboxes", options: ["Death", "Permanent Disability", "Medical Expenses", "Other"] },
        { label: "Sum Insured per Person (Ksh)", id: "sumInsuredPerPerson", type: "number" },
        { label: "Total Sum Insured (Ksh)", id: "totalSumInsured", type: "number" },
        { label: "Have you ever made a claim under personal accident insurance?", id: "claimHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "claimDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "All Risk Proposal Form": [
        { label: "Full Name of Proposer", id: "fullName", type: "text", required: true },
        { label: "Business/Occupation", id: "businessOccupation", type: "text" },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Description of Items to be Insured (Jewellery, Electronics, etc.)", id: "itemsDescription", type: "textarea" },
        { label: "Sum Insured per Item (Ksh)", id: "sumInsuredPerItem", type: "number" },
        { label: "Total Sum Insured (Ksh)", id: "totalSumInsured", type: "number" },
        { label: "Location of Items (where kept)", id: "itemsLocation", type: "text" },
        { label: "Have you ever suffered loss/damage of these items?", id: "lossHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "lossDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Work Injury Benefits Act (WIBA) Proposal Form": [
        { label: "Name of Employer/Organization", id: "employerName", type: "text", required: true },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Nature of Business/Occupation", id: "businessNature", type: "text" },
        { label: "Number of Employees", id: "employeeCount", type: "number" },
        { label: "List of Employees (Name, Age, Occupation, Salary)", id: "employeeList", type: "textarea" },
        { label: "Period of Insurance (From)", id: "periodFrom", type: "date" },
        { label: "Period of Insurance (To)", id: "periodTo", type: "date" },
        { label: "Benefits Required (Death, Permanent Disability, Medical Expenses, etc.)", id: "benefitsRequired", type: "checkboxes", options: ["Death", "Permanent Disability", "Medical Expenses", "Other"] },
        { label: "Total Annual Wages (Ksh)", id: "annualWages", type: "number" },
        { label: "Have you ever made a claim under WIBA insurance?", id: "claimHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "claimDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Employer/Authorized Person", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Fidelity Guarantee Insurance Proposal Form": [
        { label: "Name of Employer/Organization", id: "employerName", type: "text", required: true },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Nature of Business/Occupation", id: "businessNature", type: "text" },
        { label: "Number of Employees to be Insured", id: "employeeCount", type: "number" },
        { label: "List of Employees (Name, Age, Occupation, Salary)", id: "employeeList", type: "textarea" },
        { label: "Period of Insurance (From)", id: "periodFrom", type: "date" },
        { label: "Period of Insurance (To)", id: "periodTo", type: "date" },
        { label: "Sum Insured per Employee (Ksh)", id: "sumInsuredPerEmployee", type: "number" },
        { label: "Total Sum Insured (Ksh)", id: "totalSumInsured", type: "number" },
        { label: "Have you ever made a claim under fidelity guarantee insurance?", id: "claimHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "claimDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Employer/Authorized Person", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Electronic Equipment Insurance Proposal Form": [
        { label: "Full Name of Proposer", id: "fullName", type: "text", required: true },
        { label: "Business/Occupation", id: "businessOccupation", type: "text" },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Description of Equipment to be Insured (Type, Make, Model, Serial Number)", id: "equipmentDescription", type: "textarea" },
        { label: "Sum Insured per Equipment (Ksh)", id: "sumInsuredPerEquipment", type: "number" },
        { label: "Total Sum Insured (Ksh)", id: "totalSumInsured", type: "number" },
        { label: "Location of Equipment (where kept)", id: "equipmentLocation", type: "text" },
        { label: "Have you ever suffered loss/damage of this equipment?", id: "lossHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "lossDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Travel Insurance Proposal Form": [
        { label: "Full Name (as per passport)", id: "fullName", type: "text", required: true },
        { label: "Date of Birth", id: "dob", type: "date", required: true },
        { label: "Nationality", id: "nationality", type: "text" },
        { label: "Passport Number", id: "passportNumber", type: "text" },
        { label: "Phone Number", id: "phone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Destination Country", id: "destination", type: "text" },
        { label: "Purpose of Travel", id: "travelPurpose", type: "select", options: ["Business", "Leisure", "Education", "Other"] },
        { label: "Departure Date", id: "departureDate", type: "date" },
        { label: "Return Date", id: "returnDate", type: "date" },
        { label: "Do you have any pre-existing medical conditions?", id: "medicalConditions", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "medicalDetails", type: "textarea" },
        { label: "Are you traveling with family?", id: "withFamily", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please list family members (Name, Age, Relationship)", id: "familyMembers", type: "textarea" },
        { label: "Have you ever made a travel insurance claim before?", id: "claimHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "claimDetails", type: "textarea" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the information provided is true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Burglary Insurance Proposal Form": [
        { label: "Full Name of Proposer", id: "fullName", type: "text", required: true },
        { label: "Business/Occupation", id: "businessOccupation", type: "text" },
        { label: "Postal Address", id: "postalAddress", type: "text" },
        { label: "Telephone Number", id: "telephone", type: "tel" },
        { label: "Email Address", id: "email", type: "email" },
        { label: "Location of Premises (Building/Street/Plot No./Town)", id: "premisesLocation", type: "text" },
        { label: "Type of Premises", id: "premisesType", type: "select", options: ["Shop", "Warehouse", "Office", "Other"] },
        { label: "Are the premises solely occupied by you?", id: "solelyOccupied", type: "select", options: ["Yes", "No"] },
        { label: "If not, by whom?", id: "otherOccupants", type: "text" },
        { label: "Are the premises left unoccupied at night?", id: "unoccupiedAtNight", type: "select", options: ["Yes", "No"] },
        { label: "If yes, for how long?", id: "unoccupiedDuration", type: "text" },
        { label: "Describe the means of protection against burglary (locks, alarms, etc.)", id: "protectionMeans", type: "textarea" },
        { label: "Sum Insured for Stock/Contents (Ksh)", id: "sumInsuredStock", type: "number" },
        { label: "Sum Insured for Fixtures/Fittings (Ksh)", id: "sumInsuredFixtures", type: "number" },
        { label: "Sum Insured for Other Property (Ksh)", id: "sumInsuredOther", type: "number" },
        { label: "Have you ever suffered loss/damage by burglary?", id: "lossHistory", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please provide details", id: "lossDetails", type: "textarea" },
        { label: "Do you have any other insurance policies?", id: "otherPolicies", type: "select", options: ["Yes", "No"] },
        { label: "If yes, please specify", id: "otherPoliciesDetails", type: "text" },
        { label: "Declaration & Consent", id: "declaration", type: "checkbox", options: ["I hereby declare that the statements made above are true and complete. I consent to the collection and processing of my personal data for insurance purposes."] },
        { label: "Signature of Proposer", id: "signature", type: "text", required: true },
        { label: "Date", id: "date", type: "date", required: true },
    ],
    "Erection All Risks Insurance Proposal Form": [
        { label: "Title of contract (specify section(s) to be insured)", id: "contractTitle", type: "text", required: true },
        { label: "Location of Erection Site - County/Province/District", id: "siteCounty", type: "text" },
        { label: "Location of Erection Site - City/Town/Village", id: "siteCity", type: "text" },
        { label: "Name and address of principal", id: "principalNameAddress", type: "textarea" },
        { label: "Name(s) and address(es) of main contractor(s)", id: "mainContractors", type: "textarea" },
        { label: "Name(s) and address(es) of subcontractor(s)", id: "subContractors", type: "textarea" },
        { label: "Name(s) and address(es) of Manufacturer(s) of main items", id: "manufacturers", type: "textarea" },
        { label: "Name(s) and address(es) of Firm supervising erection", id: "supervisingFirm", type: "textarea" },
        { label: "Name(s) and address(es) of Consulting Engineer", id: "consultingEngineer", type: "textarea" },
        { label: "Proposer No.", id: "proposerNo", type: "text" },
        { label: "Insured No(s)", id: "insuredNos", type: "text" },
        { label: "Exact description of the property to be erected", id: "propertyDescription", type: "textarea" },
        { label: "Commencement of Insurance - Duration of Pre-storage (months)", id: "preStorageDuration", type: "text" },
        { label: "Commencement of Erection Work (months)", id: "erectionWorkDuration", type: "text" },
        { label: "Duration of Erection/Construction (months)", id: "constructionDuration", type: "text" },
        { label: "Maintenance period (months)", id: "maintenancePeriod", type: "text" },
        { label: "Duration of testing (weeks)", id: "testingDuration", type: "text" },
        { label: "If maintenance coverage required - Duration (months)", id: "maintenanceCoverageDuration", type: "text" },
        { label: "Type of coverage required", id: "coverageType", type: "text" },
        { label: "Termination of Insurance", id: "terminationInsurance", type: "text" },
        { label: "Plans/design/materials used/tested in previous constructions?", id: "previousConstructions", type: "select", options: ["Yes", "No"] },
        { label: "Details of similar projects by contractors", id: "similarProjectsDetails", type: "textarea" },
        { label: "Extension of existing plant?", id: "extensionExistingPlant", type: "select", options: ["Yes", "No"] },
        { label: "Operation of existing plant during erection?", id: "operationDuringErection", type: "select", options: ["Yes", "No"] },
        { label: "Buildings/civil engineering works already completed?", id: "buildingsCompleted", type: "select", options: ["Yes", "No"] },
        { label: "Work to be carried out by subcontractors", id: "workBySubcontractors", type: "textarea" },
        { label: "Aggravated risk of Fire?", id: "riskFire", type: "select", options: ["Yes", "No"] },
        { label: "Aggravated risk of Explosion?", id: "riskExplosion", type: "select", options: ["Yes", "No"] },
        { label: "Details of aggravated risks", id: "aggravatedRiskDetails", type: "textarea" },
        { label: "Ground water level", id: "groundWaterLevel", type: "text" },
        { label: "Nearest river, lake, sea, etc.", id: "nearestWaterBody", type: "text" },
        { label: "Distance from site", id: "distanceFromSite", type: "text" },
        { label: "Levels of river/lake/sea (low, mean, highest, mean site)", id: "waterLevels", type: "textarea" },
        { label: "Meteorological conditions (rainy seasons, rainfall, wind, storm frequency)", id: "meteorologicalConditions", type: "textarea" },
        { label: "Hazards of earthquake, volcanism, tsunami?", id: "hazardsEarthquake", type: "select", options: ["Yes", "No"] },
        { label: "Earthquakes observed in area?", id: "earthquakesObserved", type: "select", options: ["Yes", "No"] },
        { label: "Earthquake intensity/magnitude", id: "earthquakeDetails", type: "text" },
        { label: "Design based on earthquake-resistant regulations?", id: "earthquakeRegulations", type: "select", options: ["Yes", "No"] },
        { label: "Subsoil conditions", id: "subsoilConditions", type: "checkboxes", options: ["Rock", "Gravel", "Sand", "Clay", "Filled ground", "Other"] },
        { label: "Estimate probable maximum loss (% of sum insured)", id: "maxLossEstimate", type: "table", columns: ["Due to Earthquake (%)", "Due to Fire (%)", "Due to Other Cause (%)"] },
        { label: "Coverage of construction/erection equipment required?", id: "coverageEquipment", type: "select", options: ["Yes", "No"] },
        { label: "Description and replacement values of equipment", id: "equipmentDetails", type: "textarea" },
        { label: "Coverage of major machines required?", id: "coverageMachines", type: "select", options: ["Yes", "No"] },
        { label: "List of major machines and total value", id: "machinesList", type: "textarea" },
        { label: "Existing buildings/structures on/adjacent to site to be insured?", id: "existingBuildingsInsured", type: "select", options: ["Yes", "No"] },
        { label: "Third Party Liability to be included?", id: "thirdPartyLiability", type: "select", options: ["Yes", "No"] },
        { label: "Description of surrounding buildings/structures not belonging to principal/contractor", id: "surroundingBuildingsDescription", type: "textarea" },
        { label: "Cover extra charges (express freight, overtime, night work, holidays)?", id: "coverExtraCharges", type: "select", options: ["Yes", "No"] },
        { label: "Cover air freight?", id: "coverAirFreight", type: "select", options: ["Yes", "No"] },
        { label: "Details of any special extension of cover required", id: "specialExtensionDetails", type: "textarea" },
        { label: "Amounts to be insured / limits of indemnity required (Section I - Material Damage)", id: "materialDamageLimits", type: "table", columns: ["Item", "Sum to be Insured"] },
        { label: "Special risks to be insured (limits of indemnity)", id: "specialRisksLimits", type: "table", columns: ["Risk", "Limit of Indemnity"] },
        { label: "Section II - Third Party Liability (limits of indemnity)", id: "thirdPartyLimits", type: "table", columns: ["Item", "Limit of Indemnity"] },
        { label: "Declaration", id: "declaration", type: "checkbox", options: ["I declare the statements are true and complete."] },
        { label: "Consent for Data Processing", id: "dataConsent", type: "select", options: ["YES", "NO"] },
        { label: "Executed at", id: "executedAt", type: "text" },
        { label: "Date", id: "date", type: "date", required: true },
        { label: "Signature", id: "signature", type: "text", required: true },
    ],
};